services:
  mongo:
    image: mongo:7
    container_name: adaptive_ai_lms_mongo
    environment:
      MONGO_INITDB_DATABASE: adaptive_ai_lms
    ports:
      - "27017:27017"
    volumes:
      - adaptive_ai_lms_mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  adaptive_ai_lms_mongodata:
